<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01-Delete_Multiple_Job_Titles_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a18329d7-278f-4d4f-968c-ad382ea24638</testSuiteGuid>
   <testCaseLink>
      <guid>85a68879-8bcf-4a66-ab13-888d4eb35b1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2.Job_Titles_Feature/Add Job Titles/TC01-Successfully_Add_New_Job_Title</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b9cd4001-d04c-4508-9882-6046a78735f8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Job_Title_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b9cd4001-d04c-4508-9882-6046a78735f8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>desired_title</value>
         <variableId>466eee99-1bba-452d-8bf4-ad6ba3d8a74d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b9cd4001-d04c-4508-9882-6046a78735f8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Job_Description</value>
         <variableId>d21b3f37-2876-4936-8e00-761c39e0fb47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b9cd4001-d04c-4508-9882-6046a78735f8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Notes</value>
         <variableId>dccd8484-43a1-40d5-88b2-848dc043dda5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b860a9a-a5a2-4135-9bb3-ee805d998fa0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2.Job_Titles_Feature/Delete Job Titles/TC01-Successfully_Delete_Job_Title</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1a0a7c42-7ed5-4866-9428-2830fc79bf5e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Job_Title_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1a0a7c42-7ed5-4866-9428-2830fc79bf5e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>desired_title</value>
         <variableId>ff6500e2-5a17-4c6f-a5cd-b9a1e002539c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7941f8af-c79a-4936-a264-16aaa57d3aef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e34736cd-5a5e-4f89-abef-4670dc3dc6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52d9e3db-f17c-4073-8b6e-5df886d2829f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
