<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete_Title_Buttons</name>
   <tag></tag>
   <elementGuidId>08059b3d-50ee-49c2-aebe-67f53685b820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div/div[3]/div/div[2]/div[${Index_Delete}]/div/div[4]/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div/div[3]/div/div[2]/div[${Index_Delete}]/div/div[4]/div/button[1]</value>
      <webElementGuid>8f0e95ea-822f-4cbd-a73c-dca83e1a9f6e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
