<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JobTitle_Table</name>
   <tag></tag>
   <elementGuidId>1ac6ccd1-99e7-4efd-ad8d-c7b1afcd6b90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-table-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>108cff94-9d90-4e53-ae33-152a9d67482e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-table-body</value>
      <webElementGuid>d0e5d05f-12d8-4103-9ba1-e359f511ce74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>rowgroup</value>
      <webElementGuid>58428d3a-6061-4bf3-a217-48669b7bd7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account AssistantChief Executive OfficerChief Financial OfficerChief Technical OfficerContent SpecialistCustomer Success ManagerDatabase AdministratorFinance ManagerFinancial AnalystHead of SupportHR AssociateHR ManagerIT ManagerNetwork AdministratorPayroll AdministratorPre-Sales CoordinatorQA EngineerQA LeadSales RepresentativeSales5Sales5 DescSocial Media MarketerSoftware ArchitectSoftware EngineerSupport SpecialisttraineeVP - Client ServicesVP - Sales &amp; Marketing</value>
      <webElementGuid>361e854c-8825-4df5-9fa9-99792c07ad79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]/div[@class=&quot;oxd-table&quot;]/div[@class=&quot;oxd-table-body&quot;]</value>
      <webElementGuid>aa96040a-ad59-40d0-ab0c-f3de7b3e6bc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]/div/div[2]</value>
      <webElementGuid>a0e95f84-61d3-4653-b160-f3f6d2ef7c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]</value>
      <webElementGuid>421748ed-1f94-4633-95f5-5f11436fbd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Account AssistantChief Executive OfficerChief Financial OfficerChief Technical OfficerContent SpecialistCustomer Success ManagerDatabase AdministratorFinance ManagerFinancial AnalystHead of SupportHR AssociateHR ManagerIT ManagerNetwork AdministratorPayroll AdministratorPre-Sales CoordinatorQA EngineerQA LeadSales RepresentativeSales5Sales5 DescSocial Media MarketerSoftware ArchitectSoftware EngineerSupport SpecialisttraineeVP - Client ServicesVP - Sales &amp; Marketing' or . = 'Account AssistantChief Executive OfficerChief Financial OfficerChief Technical OfficerContent SpecialistCustomer Success ManagerDatabase AdministratorFinance ManagerFinancial AnalystHead of SupportHR AssociateHR ManagerIT ManagerNetwork AdministratorPayroll AdministratorPre-Sales CoordinatorQA EngineerQA LeadSales RepresentativeSales5Sales5 DescSocial Media MarketerSoftware ArchitectSoftware EngineerSupport SpecialisttraineeVP - Client ServicesVP - Sales &amp; Marketing')]</value>
      <webElementGuid>340481e8-9c0d-4020-a14b-4ac71caa015c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
