<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select</name>
   <tag></tag>
   <elementGuidId>c49c136e-3bd5-4fb0-b521-ca7229629131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[normalize-space()='${currency}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[normalize-space()='${currency}']</value>
      <webElementGuid>a8a07863-b384-4998-844b-6974b8397e8b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
