<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Find_Job_Categories</name>
   <tag></tag>
   <elementGuidId>65fcfd55-afda-4208-ad46-713596b4168b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div/div[3]/div/div[2]/div[${Index}]/div/div[2]/div</value>
      <webElementGuid>24b7a6e8-1b67-48de-8123-3ac99efa5adb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
