<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Status</name>
   <tag></tag>
   <elementGuidId>d8737204-7630-4c71-bbfe-ed155b30bcef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'${status_name}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'${status_name}')]</value>
      <webElementGuid>ed042991-db64-4808-92d4-946ddac629c0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
