<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Status</name>
   <tag></tag>
   <elementGuidId>2559d4ec-d2a1-47d6-bfc6-dd6a1a5a8f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'${Find_Name}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'${Find_Name}')]</value>
      <webElementGuid>c6a357ac-a7eb-418a-adad-824dc4b1ea13</webElementGuid>
   </webElementProperties>
</WebElementEntity>
