<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Currency_List</name>
   <tag></tag>
   <elementGuidId>9963fc13-7821-4a19-9d2a-2173f692cbe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div[2]/div/div[3]/div/div[2]/div[${Index}]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div[2]/div/div[3]/div/div[2]/div[${Index}]/div/div[2]/div</value>
      <webElementGuid>26b4dc93-9785-464a-a988-41535e43cee2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
