<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Currency</name>
   <tag></tag>
   <elementGuidId>7b4c960b-9168-45ac-b326-425839bd868f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'${Find_Currency}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'${Find_Currency}')]</value>
      <webElementGuid>f1da5186-3e03-4867-96ae-68ed377247ad</webElementGuid>
   </webElementProperties>
</WebElementEntity>
