<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Job_Categories</name>
   <tag></tag>
   <elementGuidId>7b8bdab2-6a07-4482-9621-e7c6ba0fa625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'${verify_job}')]</value>
      <webElementGuid>a10070bd-83a5-43f9-bc45-d62f7288fc50</webElementGuid>
   </webElementProperties>
</WebElementEntity>
