<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01-Edit_Currency_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>02b0c6dd-d649-4cbd-aebf-d12f957b87a6</testSuiteGuid>
   <testCaseLink>
      <guid>fa451cd6-d242-4d14-8db3-c71085335b0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/3.Pay_Grade_Feature/Edit Currency/TC01-Successfully_Edit_Minimum_Salary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b5c4fef-c78c-467a-ad7f-c7f08c5a428a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa5901ed-e60e-41d2-8ffc-744d3f8306d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f2c5549-0637-48bd-97d8-a5f2d60662c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/3.Pay_Grade_Feature/Edit Currency/TC02-Successfully_Edit_Maximum_Salary</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b44933e-26f3-43d8-9277-22a4befb00c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60949cc3-ac9e-484d-896a-7316abefe22c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d1e7dd7-1106-46e4-a785-a3145c04f1db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/3.Pay_Grade_Feature/Edit Currency/TC03-User_Enter_Minimum_Salary_Higher</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3282a0af-59c2-45e8-811c-61f120457636</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2b3cae-3214-4e44-988f-ef8c1737de3a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
